version: "3"

 
# env config 반영 필요(front: frontaddress, backaddress / back: port, mongo config)
services:
  nara-back:
    image: nara_back
    stdin_open: true
    ports:
      - "5000:5000"
  nara-front:
    image: nara_front
    stdin_open: true
    ports:
      - "3000:3000"




